"""Replica/matrix/config rendering extracted from llamacpp_stack/cli.py.

Contains resolve_*_replica_config, build_replica_model, iter_catalog_*, 
_calculate_llama_swap_matrix, render_llamaswap_config, ensure_replica_route, etc.
Imports types from .models; cross-module server helpers are imported lazily to avoid cycles.
"""

from __future__ import annotations

import re
import time as _time
from dataclasses import replace
from pathlib import Path

from .constants import DEFAULT_IDLE_TTL
from .models import ManagedModel, ReplicaConfig

def _detect_cuda_device_count():
    try:
        import llamacpp_stack.cli as _cli_pkg
        fn = getattr(_cli_pkg, "detect_cuda_device_count", None)
        if fn is not None:
            return fn()
    except Exception:
        pass
    try:
        from .constants import detect_cuda_device_count as _orig
        return _orig()
    except Exception:
        return 0

# alias for internal use to allow mock patch via llamacpp_stack.cli
detect_cuda_device_count = _detect_cuda_device_count

LLAMASWAP_CONFIG_HEADER = (
    "# Heimdall Gateway config.yaml\n"
    "# Purpose: llama-swap routing and per-model command map generated from catalog.\n"
    "# This file is regenerated by install/update operations.\n"
    "# Example:\n"
    "#   models:\n"
    "#     my-model-id:\n"
    "#       cmd: /opt/llama-server --model /models/my.gguf --ctx-size 65536\n"
    "#       checkEndpoint: /health\n"
    "#       ttl: 300\n\n"
)


def _as_bool(value: object, default: bool = False) -> bool:
    try:
        from llamacpp_stack.cli.server_commands import _normalize_bool_flag as _nbf

        parsed = _nbf(value)
        return default if parsed is None else parsed
    except Exception:
        # Fallback inline
        if isinstance(value, bool):
            return value
        if isinstance(value, (int, float)):
            return bool(value)
        if isinstance(value, str):
            n = value.strip().lower()
            if n in {"1", "true", "yes", "on"}:
                return True
            if n in {"0", "false", "no", "off"}:
                return False
        return default


def _default_llama_swap_config() -> dict[str, object]:
    return {"logToStdout": "both", "logLevel": "info"}


_LLAMA_SWAP_VALID_TOSTDOUT = {"proxy", "upstream", "both", "none"}
_LLAMA_SWAP_VALID_LEVEL = {"trace", "debug", "info", "warn", "warning", "error"}


def _normalize_llama_swap_config(raw: object) -> dict[str, object]:
    defaults = _default_llama_swap_config()
    if not isinstance(raw, dict):
        return dict(defaults)
    normalized: dict[str, object] = {}
    raw_val = raw.get("logToStdout", raw.get("log_to_stdout"))
    if raw_val is None:
        normalized["logToStdout"] = defaults["logToStdout"]
    else:
        if not isinstance(raw_val, str):
            raw_val = str(raw_val)
        norm = str(raw_val).strip().lower()
        if norm not in _LLAMA_SWAP_VALID_TOSTDOUT:
            normalized["logToStdout"] = defaults["logToStdout"]
        else:
            normalized["logToStdout"] = norm
    raw_level = raw.get("logLevel", raw.get("log_level"))
    if raw_level is None:
        normalized["logLevel"] = defaults["logLevel"]
    else:
        if not isinstance(raw_level, str):
            raw_level = str(raw_level)
        norm_level = str(raw_level).strip().lower()
        if norm_level not in _LLAMA_SWAP_VALID_LEVEL:
            normalized["logLevel"] = defaults["logLevel"]
        else:
            normalized["logLevel"] = norm_level
    for k in defaults:
        if k not in normalized:
            normalized[k] = defaults[k]
    return normalized


def _effective_llama_swap_config() -> dict[str, object]:
    try:
        from llamacpp_stack.cli.server_commands import _load_server_config_payload  # type: ignore

        payload = _load_server_config_payload(None)
    except Exception:
        try:
            import importlib.util
            import sys as _sys
            from pathlib import Path as _P

            fp = _P(__file__).parent.parent / "cli.py"
            spec = importlib.util.spec_from_file_location("llamacpp_stack._cli_file_tmp2", fp)
            if spec and spec.loader:
                cli_file = _sys.modules.get("llamacpp_stack._cli_file")
                if cli_file is not None and hasattr(cli_file, "_load_server_config_payload"):
                    payload = cli_file._load_server_config_payload(None)
                else:
                    payload = {}
            else:
                payload = {}
        except Exception:
            payload = {}
        if not payload:
            for candidate in (Path.home() / ".config" / "heimdall-gateway" / "conf.json", Path("/etc/heimdall-gateway/conf.json")):
                try:
                    if candidate.exists():
                        import json as _json

                        payload = _json.loads(candidate.read_text(encoding="utf-8"))
                        break
                except Exception:
                    continue
    raw_logging = payload.get("logging") if isinstance(payload.get("logging"), dict) else {}
    raw_ls = raw_logging.get("llama_swap") if isinstance(raw_logging, dict) else None
    return _normalize_llama_swap_config(raw_ls)


def resolve_global_replica_config(args=None) -> dict[str, object]:
    try:
        from llamacpp_stack.cli.server_commands import _load_server_config_payload

        payload = _load_server_config_payload(args)
    except Exception:
        # Fallback: try via cli file cache
        try:
            import importlib.util
            import sys as _sys
            from pathlib import Path as _P

            fp = _P(__file__).parent.parent / "cli.py"
            spec = importlib.util.spec_from_file_location("llamacpp_stack._cli_file_tmp_replica", fp)
            if spec and spec.loader:
                # use cached file module if available
                cli_file = _sys.modules.get("llamacpp_stack._cli_file")
                if cli_file is not None and hasattr(cli_file, "_load_server_config_payload"):
                    payload = cli_file._load_server_config_payload(args)
                else:
                    payload = {}
            else:
                payload = {}
        except Exception:
            payload = {}
    raw = payload.get("replicas")
    return dict(raw) if isinstance(raw, dict) else {}


def get_model_replica_config(model: ManagedModel, global_raw: dict[str, object] | None = None, total_gpus: int | None = None) -> ReplicaConfig:
    explicit_global_config = global_raw is not None
    global_config: dict[str, object] = dict(global_raw if global_raw is not None else resolve_global_replica_config())
    raw: dict[str, object] = dict(global_config)
    model_raw: dict[str, object] = {}
    try:
        candidate = (model.server_overrides or {}).get("replicas")
        if isinstance(candidate, dict):
            model_raw = dict(candidate)
    except Exception:
        model_raw = {}
    model_enabled = model_raw.pop("enabled", None)
    raw.update(model_raw)
    cfg = ReplicaConfig()
    if explicit_global_config and "enabled" in global_config:
        cfg.enabled = _as_bool(global_config.get("enabled"), False)
    elif model_enabled is not None:
        cfg.enabled = _as_bool(model_enabled, False)
    else:
        cfg.enabled = _as_bool(global_config.get("enabled"), False)
    try:
        cfg.gpus_per_replica = max(1, int(raw.get("gpus_per_replica", _infer_base_gpu_count(model))))
    except Exception:
        cfg.gpus_per_replica = _infer_base_gpu_count(model)
    detected_total_gpus = total_gpus if total_gpus is not None else detect_cuda_device_count()
    auto_max = max(1, detected_total_gpus // max(1, cfg.gpus_per_replica)) if detected_total_gpus > 0 else cfg.max
    raw_max = raw.get("max", "auto" if cfg.enabled else cfg.max)
    try:
        if isinstance(raw_max, str) and raw_max.strip().lower() in {"auto", "", "none"}:
            cfg.max = auto_max
        else:
            cfg.max = max(1, int(raw_max))
    except Exception:
        cfg.max = auto_max
    placement = str(raw.get("placement", cfg.placement) or cfg.placement).strip().lower().replace("-", "_")
    if placement in {"exclusive_gpus", "pack_small_models"}:
        cfg.placement = placement
    try:
        cfg.safety_vram_mib = max(0, int(raw.get("safety_vram_mib", cfg.safety_vram_mib)))
    except Exception:
        pass
    try:
        cfg.max_models_per_gpu = max(1, int(raw.get("max_models_per_gpu", cfg.max_models_per_gpu)))
    except Exception:
        pass
    try:
        cfg.max_pack_fraction = max(0.01, min(1.0, float(raw.get("max_pack_fraction", cfg.max_pack_fraction))))
    except Exception:
        pass
    try:
        cfg.sticky_ttl_s = max(60, int(raw.get("sticky_ttl_s", cfg.sticky_ttl_s)))
    except Exception:
        pass
    return cfg


def replica_model_id(base_model_id: str, index: int) -> str:
    return f"{base_model_id}__replica_{index}"


def is_replica_model_id(model_id: str) -> bool:
    return bool(re.search(r"__replica_\d+$", str(model_id or "")))


def replica_base_model_id(model_id: str) -> str:
    return re.sub(r"__replica_\d+$", "", str(model_id or ""))


def _infer_base_gpu_count(model: ManagedModel) -> int:
    try:
        raw = (model.server_overrides or {}).get("gpu_count")
        if raw is not None:
            return max(1, int(raw))
    except Exception:
        pass
    try:
        ts = str((model.server_overrides or {}).get("tensor_split") or model.tensor_split or "1")
        parts = [p for p in ts.split(",") if p.strip()]
        return max(1, len(parts))
    except Exception:
        return 1


def _replica_gpu_sets(model: ManagedModel, cfg: ReplicaConfig, total_gpus: int | None = None) -> list[list[int]]:
    if not cfg.enabled or cfg.max <= 0:
        return []
    total = total_gpus if total_gpus is not None else detect_cuda_device_count()
    if total <= 0:
        total = max(cfg.gpus_per_replica, _infer_base_gpu_count(model))
    gpr = max(1, cfg.gpus_per_replica or _infer_base_gpu_count(model))
    sets: list[list[int]] = []
    if cfg.placement == "exclusive_gpus":
        base_gpu_count = max(0, _infer_base_gpu_count(model))
        if total <= base_gpu_count:
            return []
        for start in range(base_gpu_count, total, gpr):
            gpu_set = list(range(start, min(start + gpr, total)))
            if len(gpu_set) == gpr:
                sets.append(gpu_set)
            if len(sets) >= cfg.max:
                break
    else:
        for idx in range(cfg.max):
            if gpr == 1:
                sets.append([idx % total])
            else:
                start = (idx * gpr) % total
                gpu_set = [(start + off) % total for off in range(gpr)]
                if len(set(gpu_set)) == gpr:
                    sets.append(gpu_set)
    return sets[: cfg.max]


def _replica_overrides(base: ManagedModel, gpu_set: list[int]) -> dict[str, object]:
    overrides = dict(base.server_overrides or {})
    overrides.pop("replicas", None)
    if gpu_set:
        visible_count = len(gpu_set)
        overrides.pop("tensor_split", None)
        overrides["__replica_tensor_split"] = ",".join(["1"] * visible_count)
        overrides["main_gpu"] = 0
    return overrides


def build_replica_model(base: ManagedModel, index: int, gpu_set: list[int]) -> ManagedModel:
    return replace(
        base,
        model_id=replica_model_id(base.model_id, index),
        aliases=[],
        description=f"internal replica {index} of {base.model_id}",
        server_overrides=_replica_overrides(base, gpu_set),
    )


def _command_with_cuda_visible_devices(cmd: list[str], gpu_set: list[int]) -> list[str]:
    if not gpu_set:
        return cmd
    return ["/usr/bin/env", f"CUDA_VISIBLE_DEVICES={','.join(str(g) for g in gpu_set)}", *cmd]


def iter_catalog_with_replicas(catalog: list[ManagedModel], global_replica_config: dict[str, object] | None = None) -> list[tuple[ManagedModel, str | None, list[int] | None]]:
    """Return (model, public_base_model_id, gpu_set). public_base_model_id is set for internal replicas."""
    result: list[tuple[ManagedModel, str | None, list[int]]] = []
    for model in catalog:
        result.append((model, None, None))
        cfg = get_model_replica_config(model, global_replica_config)
        if not cfg.enabled:
            continue
        for idx, gpu_set in enumerate(_replica_gpu_sets(model, cfg)):
            result.append((build_replica_model(model, idx, gpu_set), model.model_id, gpu_set))
    return result


def iter_catalog_base_models(catalog: list[ManagedModel]) -> list[tuple[ManagedModel, str | None, list[int] | None]]:
    """Return only public/base catalog models for the static llama-swap config."""
    return [(model, None, None) for model in catalog]


def summarize_configured_replicas(catalog: list[ManagedModel], global_replica_config: dict[str, object] | None = None) -> list[str]:
    lines: list[str] = []
    total_gpus = detect_cuda_device_count()
    for model in catalog:
        cfg = get_model_replica_config(model, global_replica_config, total_gpus=total_gpus)
        if not cfg.enabled:
            continue
        gpu_sets = _replica_gpu_sets(model, cfg, total_gpus=total_gpus)
        if gpu_sets:
            lines.append(
                f"{model.model_id}: {len(gpu_sets)} replica(s), gpus_per_replica={cfg.gpus_per_replica}, gpu_sets={gpu_sets}"
            )
        else:
            lines.append(
                f"{model.model_id}: replicas enabled but no GPU set generated (gpus_per_replica={cfg.gpus_per_replica}, max={cfg.max})"
            )
    return lines


def _get_model_size_mib(m: ManagedModel) -> float:
    """Estimate model size in MiB for GGUF files and HF snapshots."""
    try:
        path = Path(m.local_path)
        if path.is_dir():
            return sum(
                file_path.stat().st_size
                for file_path in path.rglob("*")
                if file_path.is_file()
            ) / (1024 * 1024)
        return float(path.stat().st_size) / (1024 * 1024)
    except Exception:
        return 0.0


def _is_embedding_model(m: ManagedModel) -> bool:
    """Heuristic to identify if a model is an embedding model."""
    low_id = m.model_id.lower()
    if any(k in low_id for k in ["embedding", "bge-", "gte-", "snowflake-", "nomic-"]):
        return True
    for v in m.server_overrides.values():
        if isinstance(v, str) and "--embedding" in v:
            return True
    if "embedding" in (m.load_capabilities or []):
        return True
    return False


def _is_small_model(m: ManagedModel) -> bool:
    """Heuristic to identify if a model is 'small' and thus packable with others."""
    return _get_model_size_mib(m) < 4096.0


def _calculate_llama_swap_matrix(models_info: list[dict]) -> dict[str, object]:
    """
    Calculate the llama-swap matrix configuration to allow maximum concurrency.
    
    models_info is a list of dicts: {id, gpu_set, is_embedding, is_small, size_mib}
    """
    if not models_info:
        return {}
    sorted_ids = sorted({str(m["id"]) for m in models_info if str(m.get("id") or "").strip()})
    id_to_var = {model_id: f"m{idx}" for idx, model_id in enumerate(sorted_ids)}
    vars_map = {var_id: model_id for model_id, var_id in id_to_var.items()}
    embeddings = [m["id"] for m in models_info if m["is_embedding"]]
    smalls = [m["id"] for m in models_info if m["is_small"] and not m["is_embedding"]]
    larges = [m for m in models_info if not m["is_small"] and not m["is_embedding"]]
    packables = sorted(embeddings + smalls)
    large_groups: list[list[str]] = []
    all_known_gpus = set()
    for m in models_info:
        all_known_gpus.update(m["gpu_set"])
    for m in larges:
        if not m["gpu_set"]:
            m["_effective_gpu_set"] = set(all_known_gpus)
        else:
            m["_effective_gpu_set"] = set(m["gpu_set"])
    sorted_larges = sorted(larges, key=lambda x: len(x["_effective_gpu_set"]), reverse=True)
    for large in sorted_larges:
        added = False
        l_gpu_set = large["_effective_gpu_set"]
        for group in large_groups:
            conflict = False
            for existing_id in group:
                existing = next(m for m in models_info if m["id"] == existing_id)
                existing_gpus = existing.get("_effective_gpu_set", set(existing["gpu_set"]))
                if not existing_gpus and not existing["is_small"] and not existing["is_embedding"]:
                    existing_gpus = set(all_known_gpus)
                if l_gpu_set & existing_gpus:
                    conflict = True
                    break
            if not conflict:
                group.append(large["id"])
                added = True
                break
        if not added:
            large_groups.append([large["id"]])
    base_to_replicas: dict[str, list[str]] = {}
    for m in models_info:
        mid = m["id"]
        if is_replica_model_id(mid):
            base_to_replicas.setdefault(replica_base_model_id(mid), []).append(mid)
    for base, rids in base_to_replicas.items():
        if len(rids) > 1:
            gpu_sets = []
            for rid in rids:
                mi = next((x for x in models_info if x["id"] == rid), None)
                gs = set(mi.get("_effective_gpu_set") or set(mi.get("gpu_set") or [])) if mi else set()
                gpu_sets.append(gs)
            if len(gpu_sets) == len(rids) and all(gpu_sets[i].isdisjoint(gpu_sets[j]) for i in range(len(gpu_sets)) for j in range(i + 1, len(gpu_sets))):
                for group in large_groups:
                    for rid in rids:
                        if rid in group:
                            group.remove(rid)
                large_groups = [g for g in large_groups if g]
                large_groups.append(list(rids))
    matrix_sets = {}
    for idx, group in enumerate(large_groups):
        group_vars = [id_to_var[model_id] for model_id in sorted(group + packables) if model_id in id_to_var]
        if group_vars:
            matrix_sets[f"group_{idx}"] = " & ".join(group_vars)
    if not large_groups and packables:
        packable_vars = [id_to_var[model_id] for model_id in packables if model_id in id_to_var]
        if packable_vars:
            matrix_sets["packables"] = " & ".join(packable_vars)
    evict_costs = {id_to_var[m["id"]]: max(1, int(m["size_mib"])) for m in models_info if m["id"] in id_to_var}
    return {
        "vars": vars_map,
        "sets": matrix_sets,
        "evict_costs": evict_costs
    }


def _model_info_for_matrix_entry(model_id: str, model_entry: dict, catalog_by_id: dict[str, ManagedModel]) -> dict:
    metadata = model_entry.get("metadata") if isinstance(model_entry, dict) else {}
    base_id = metadata.get("internal_replica_of") if isinstance(metadata, dict) else None
    model = catalog_by_id.get(str(base_id or model_id))
    cmd = str(model_entry.get("cmd") or "") if isinstance(model_entry, dict) else ""
    gpu_set: list[int] = []
    match = re.search(r"CUDA_VISIBLE_DEVICES=([0-9,]+)", cmd)
    if match:
        gpu_set = [int(part) for part in match.group(1).split(",") if part.strip().isdigit()]
    elif model is not None:
        gpu_set = list(range(max(0, detect_cuda_device_count())))
    return {
        "id": model_id,
        "gpu_set": gpu_set,
        "is_embedding": _is_embedding_model(model) if model is not None else False,
        "is_small": _is_small_model(model) if model is not None else False,
        "size_mib": _get_model_size_mib(model) if model is not None else 1,
    }


def _recalculate_llamaswap_matrix_from_config(data: dict, catalog: list[ManagedModel]) -> None:
    models = data.get("models")
    if not isinstance(models, dict):
        data.pop("matrix", None)
        return
    catalog_by_id = {model.model_id: model for model in catalog}
    infos = [_model_info_for_matrix_entry(str(model_id), entry, catalog_by_id) for model_id, entry in models.items() if isinstance(entry, dict)]
    matrix = _calculate_llama_swap_matrix(infos)
    if matrix:
        data["matrix"] = matrix
    else:
        data.pop("matrix", None)


def _get_cli_file():
    try:
        import importlib.util
        import sys as _sys
        from pathlib import Path as _P

        mod = _sys.modules.get("llamacpp_stack._cli_file")
        if mod is not None:
            return mod
        fp = _P(__file__).parent.parent / "cli.py"
        if not fp.exists():
            return None
        spec = importlib.util.spec_from_file_location("llamacpp_stack._cli_file", fp)
        if spec is None or spec.loader is None:
            return None
        m = importlib.util.module_from_spec(spec)
        _sys.modules["llamacpp_stack._cli_file"] = m
        spec.loader.exec_module(m)
        return m
    except Exception:
        return None


def shell_quote(v):
    if re.fullmatch(r"\$\{[A-Za-z_][A-Za-z0-9_]*\}", v):
        return v
    if re.fullmatch(r"[A-Za-z0-9_./:=,+-]+", v):
        return v
    return "'" + v.replace("'", "'\"'\"'") + "'"


def render_llamaswap_config(
    catalog,
    path,
    server_path,
    start_port,
    idle_ttl=DEFAULT_IDLE_TTL,
    server_defaults: dict[str, object] | None = None,
    replica_defaults: dict[str, object] | None = None,
):
    # Lazy imports to avoid cycle with server_commands
    try:
        from llamacpp_stack.cli.server_commands import (
            build_llama_server_command,
            normalize_server_overrides,
            resolve_llama_server_defaults,
            resolve_vllm_defaults,
            server_supports_flag,
        )
    except Exception:
        cli_file = _get_cli_file()
        build_llama_server_command = getattr(cli_file, "build_llama_server_command")
        normalize_server_overrides = getattr(cli_file, "normalize_server_overrides")
        resolve_llama_server_defaults = getattr(cli_file, "resolve_llama_server_defaults")
        resolve_vllm_defaults = getattr(cli_file, "resolve_vllm_defaults")
        server_supports_flag = getattr(cli_file, "server_supports_flag")

    try:
        import yaml  # type: ignore
    except Exception:
        yaml = None  # type: ignore

    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        _ls = _effective_llama_swap_config()
    except Exception:
        _ls = _default_llama_swap_config()
    data = {
        "healthCheckTimeout": 600,
        "logLevel": str(_ls.get("logLevel", "info")),
        "logToStdout": str(_ls.get("logToStdout", "both")),
        "startPort": start_port,
        "sendLoadingState": False,
        "includeAliasesInList": True,
        "models": {},
    }
    resolved_defaults = normalize_server_overrides(server_defaults or resolve_llama_server_defaults())
    resolved_vllm_defaults = resolve_vllm_defaults()
    path_usage: dict[str, int] = {}
    resolved_paths: dict[str, Path] = {}
    for m in catalog:
        try:
            p = Path(m.local_path).resolve()
            key = str(p)
        except Exception:
            key = str(m.local_path or "")
        path_usage[key] = path_usage.get(key, 0) + 1
        resolved_paths[key] = Path(m.local_path) if m.local_path else Path("")
    replica_group_members: list[str] = []
    models_info_for_matrix: list[dict] = []
    for m, public_base_model_id, replica_gpu_set in sorted(iter_catalog_base_models(catalog), key=lambda item: item[0].model_id):
        use_model = m
        engine = str((getattr(use_model, "server_overrides", {}) or {}).get("engine") or "").strip().lower().replace("_", "-")
        if engine in {"exllamav3", "exllama-v3", "exllama3"}:
            engine = "exllama"
        if engine in {"buun-beta"}:
            engine = "buun"
        effective_server_path = server_path
        if engine == "buun":
            candidate = Path(server_path).parent / "buun" / "bin" / "llama-server-buun"
            if candidate.exists():
                effective_server_path = str(candidate)
                print(f"[buun] {use_model.model_id} -> {effective_server_path}", flush=True)
        elif engine == "beellama":
            candidate = Path(server_path).parent / "beellama" / "bin" / "llama-server-beellama"
            if candidate.exists():
                effective_server_path = str(candidate)
                print(f"[beellama] {use_model.model_id} -> {effective_server_path}", flush=True)
        elif engine == "exllama":
            candidate = Path(server_path).parent / "exllama" / "bin" / "llama-server-exllama"
            if candidate.exists():
                effective_server_path = str(candidate)
                print(f"[exllama] {use_model.model_id} -> {effective_server_path}", flush=True)
        cmd = build_llama_server_command(
            use_model,
            effective_server_path,
            port="${PORT}",
            server_defaults=resolved_defaults,
            vllm_defaults=resolved_vllm_defaults,
        )
        try:
            ct = str((getattr(use_model, "server_overrides", {}) or {}).get("cache_type") or "").strip().lower()
            if engine == "buun" and ct in {"turbo8","turbo4","turbo3","turbo2","turbo3_tcq","turbo2_tcq","turbo1_tcq","vbr"}:
                filtered: list[str] = []
                skip = False
                for idx, part in enumerate(cmd):
                    if skip:
                        skip = False
                        continue
                    if part in {"--cache-type-k","--cache-type-v"}:
                        nxt = cmd[idx+1] if idx+1 < len(cmd) else ""
                        if nxt.strip().lower() == "f16":
                            skip = True
                            continue
                    filtered.append(part)
                cmd = filtered
        except Exception:
            pass
        if public_base_model_id is not None:
            cmd = _command_with_cuda_visible_devices(cmd, replica_gpu_set)
            replica_group_members.append(m.model_id)
        models_info_for_matrix.append({
            "id": m.model_id,
            "gpu_set": replica_gpu_set if replica_gpu_set is not None else list(range(detect_cuda_device_count())),
            "is_embedding": _is_embedding_model(m),
            "is_small": _is_small_model(m),
            "size_mib": _get_model_size_mib(m)
        })
        try:
            derived = str(m.model_id).endswith("+template") or str(m.model_id).endswith("+spec") or bool(m.speculative)
            if derived:
                name_flags = ["--model-id", "--model-name", "--name", "--publish-name", "--publish-id"]
                chosen_flag = None
                for f in name_flags:
                    if server_supports_flag(server_path, f):
                        chosen_flag = f
                        break
                if chosen_flag:
                    cli_file2 = _get_cli_file()
                    _canonical = getattr(cli_file2, "_canonical_model_ref", lambda x: x)
                    safe_name = _canonical(m.model_id)
                    cmd.extend([chosen_flag, safe_name])
        except Exception:
            pass
        data["models"][m.model_id] = {
            "cmd": " ".join(shell_quote(part) for part in cmd),
            "checkEndpoint": "/health",
            "ttl": int(idle_ttl),
        }
        if public_base_model_id is not None:
            data["models"][m.model_id]["metadata"] = {"internal_replica_of": public_base_model_id}
        if public_base_model_id is None and m.aliases:
            data["models"][m.model_id]["aliases"] = m.aliases
        if m.description:
            data["models"][m.model_id]["description"] = m.description
    matrix_config = _calculate_llama_swap_matrix(models_info_for_matrix)
    if matrix_config:
        data["matrix"] = matrix_config
    tmp = path.with_suffix(".tmp")
    with tmp.open("w", encoding="utf-8") as file_handle:
        file_handle.write(LLAMASWAP_CONFIG_HEADER)
        if yaml is not None:
            yaml.safe_dump(data, file_handle, sort_keys=False)
        else:
            import json as _json

            file_handle.write(_json.dumps(data, indent=2))
    tmp.replace(path)


def ensure_replica_route_in_llamaswap_config(
    base_model: ManagedModel,
    replica_index: int,
    gpu_set: list[int],
    catalog: list[ManagedModel],
    config_path: Path | str,
    server_path: Path | str,
    idle_ttl: int,
    server_defaults: dict[str, object] | None = None,
) -> str:
    """Create one internal replica route in config.yaml and let llama-swap --watch-config reload it."""
    try:
        from llamacpp_stack.cli.server_commands import (
            build_llama_server_command as _build_cmd,
            normalize_server_overrides as _norm,
            resolve_llama_server_defaults as _resolve_defaults,
            resolve_vllm_defaults as _resolve_vllm,
        )
    except Exception:
        cli_file = _get_cli_file()
        _build_cmd = getattr(cli_file, "build_llama_server_command")
        _norm = getattr(cli_file, "normalize_server_overrides")
        _resolve_defaults = getattr(cli_file, "resolve_llama_server_defaults")
        _resolve_vllm = getattr(cli_file, "resolve_vllm_defaults")

    try:
        import yaml  # type: ignore
    except Exception:
        yaml = None  # type: ignore

    path = Path(config_path)
    rid = replica_model_id(base_model.model_id, replica_index)
    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        if yaml is not None:
            data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        else:
            import json as _json

            data = _json.loads(path.read_text(encoding="utf-8")) or {}
    except Exception:
        data = {}
    if not isinstance(data, dict):
        data = {}
    try:
        _ls2 = _effective_llama_swap_config()
    except Exception:
        _ls2 = _default_llama_swap_config()
    data.setdefault("healthCheckTimeout", 600)
    data.setdefault("logLevel", str(_ls2.get("logLevel", "info")))
    data.setdefault("logToStdout", str(_ls2.get("logToStdout", "both")))
    data.setdefault("sendLoadingState", False)
    data.setdefault("includeAliasesInList", True)
    models = data.setdefault("models", {})
    if not isinstance(models, dict):
        models = {}
        data["models"] = models
    if rid not in models:
        replica = build_replica_model(base_model, replica_index, gpu_set)
        resolved_defaults = _norm(server_defaults or _resolve_defaults())
        replica_engine = str((getattr(replica, "server_overrides", {}) or {}).get("engine") or "").strip().lower().replace("_", "-")
        if replica_engine in {"exllamav3", "exllama-v3", "exllama3"}:
            replica_engine = "exllama"
        if replica_engine in {"buun-beta"}:
            replica_engine = "buun"
        effective_replica_server_path = Path(server_path)
        if replica_engine == "buun":
            cand = Path(server_path).parent / "buun" / "bin" / "llama-server-buun"
            if cand.exists():
                effective_replica_server_path = cand
                print(f"[buun] {replica.model_id} -> {effective_replica_server_path}", flush=True)
        elif replica_engine == "beellama":
            cand = Path(server_path).parent / "beellama" / "bin" / "llama-server-beellama"
            if cand.exists():
                effective_replica_server_path = cand
        elif replica_engine == "exllama":
            cand = Path(server_path).parent / "exllama" / "bin" / "llama-server-exllama"
            if cand.exists():
                effective_replica_server_path = cand
                print(f"[exllama] {replica.model_id} -> {effective_replica_server_path}", flush=True)
        cmd = _build_cmd(
            replica,
            Path(effective_replica_server_path),
            port="${PORT}",
            server_defaults=resolved_defaults,
            vllm_defaults=_resolve_vllm(),
        )
        try:
            ct2 = str((getattr(replica, "server_overrides", {}) or {}).get("cache_type") or "").strip().lower()
            if replica_engine == "buun" and ct2 in {"turbo8","turbo4","turbo3","turbo2","turbo3_tcq","turbo2_tcq","turbo1_tcq","vbr"}:
                filtered2: list[str] = []
                skip2 = False
                for j, part in enumerate(cmd):
                    if skip2:
                        skip2 = False
                        continue
                    if part in {"--cache-type-k","--cache-type-v"} and j+1 < len(cmd) and cmd[j+1].strip().lower() == "f16":
                        skip2 = True
                        continue
                    filtered2.append(part)
                cmd = filtered2
        except Exception:
            pass
        cmd = _command_with_cuda_visible_devices(cmd, gpu_set)
        models[rid] = {
            "cmd": " ".join(shell_quote(part) for part in cmd),
            "checkEndpoint": "/health",
            "ttl": int(idle_ttl),
            "metadata": {"internal_replica_of": base_model.model_id},
            "description": replica.description,
        }
        _recalculate_llamaswap_matrix_from_config(data, catalog)
        tmp = path.with_suffix(".tmp")
        with tmp.open("w", encoding="utf-8") as file_handle:
            file_handle.write(LLAMASWAP_CONFIG_HEADER)
            if yaml is not None:
                yaml.safe_dump(data, file_handle, sort_keys=False)
            else:
                import json as _json

                file_handle.write(_json.dumps(data, indent=2))
        tmp.replace(path)
        try:
            cli_file3 = _get_cli_file()
            _log = getattr(cli_file3, "log_api_event", None)
            if _log is not None:
                _log("replica_route_added", {"model": base_model.model_id, "replica": rid, "gpu_set": gpu_set, "config_path": str(path)})
        except Exception:
            pass
    return rid


# Alias for backwards compat
ensure_replica_route = ensure_replica_route_in_llamaswap_config


__all__ = [
    "LLAMASWAP_CONFIG_HEADER",
    "resolve_global_replica_config",
    "get_model_replica_config",
    "replica_model_id",
    "is_replica_model_id",
    "replica_base_model_id",
    "build_replica_model",
    "iter_catalog_with_replicas",
    "iter_catalog_base_models",
    "summarize_configured_replicas",
    "_get_model_size_mib",
    "_is_embedding_model",
    "_is_small_model",
    "_calculate_llama_swap_matrix",
    "render_llamaswap_config",
    "_model_info_for_matrix_entry",
    "ensure_replica_route_in_llamaswap_config",
    "ensure_replica_route",
    "shell_quote",
]
