"""Replica/matrix/config rendering extracted from llamacpp_stack/cli.py.

Contains resolve_*_replica_config, build_replica_model, iter_catalog_*, 
_calculate_llama_swap_matrix, render_llamaswap_config, ensure_replica_route, etc.
Imports types from .models; cross-module server helpers are imported lazily to avoid cycles.
"""

from __future__ import annotations

import re
import time as _time
from dataclasses import replace
from pathlib import Path

from .constants import DEFAULT_IDLE_TTL
from .models import ManagedModel, ReplicaConfig
from .vision import (
    cached_mmproj_config,
    resolve_render_include_mmproj,
    vision_route_ttl,
)

def _detect_cuda_device_count():
    try:
        import llamacpp_stack.cli as _cli_pkg
        fn = getattr(_cli_pkg, "detect_cuda_device_count", None)
        if fn is not None:
            return fn()
    except Exception:
        pass
    try:
        from .constants import detect_cuda_device_count as _orig
        return _orig()
    except Exception:
        return 0

# alias for internal use to allow mock patch via llamacpp_stack.cli
detect_cuda_device_count = _detect_cuda_device_count

LLAMASWAP_CONFIG_HEADER = (
    "# LLM Server config.yaml\n"
    "# Purpose: llama-swap routing and per-model command map generated from catalog.\n"
    "# This file is regenerated by install/update operations.\n"
    "# Example:\n"
    "#   models:\n"
    "#     my-model-id:\n"
    "#       cmd: /opt/llama-server --model /models/my.gguf --ctx-size 65536\n"
    "#       checkEndpoint: /health\n"
    "#       ttl: 300\n\n"
)


def _as_bool(value: object, default: bool = False) -> bool:
    try:
        from llamacpp_stack.cli.server_commands import _normalize_bool_flag as _nbf

        parsed = _nbf(value)
        return default if parsed is None else parsed
    except Exception:
        # Fallback inline
        if isinstance(value, bool):
            return value
        if isinstance(value, (int, float)):
            return bool(value)
        if isinstance(value, str):
            n = value.strip().lower()
            if n in {"1", "true", "yes", "on"}:
                return True
            if n in {"0", "false", "no", "off"}:
                return False
        return default


def _default_llama_swap_config() -> dict[str, object]:
    return {"logToStdout": "both", "logLevel": "info"}


_LLAMA_SWAP_VALID_TOSTDOUT = {"proxy", "upstream", "both", "none"}
_LLAMA_SWAP_VALID_LEVEL = {"trace", "debug", "info", "warn", "warning", "error"}


def _normalize_llama_swap_config(raw: object) -> dict[str, object]:
    defaults = _default_llama_swap_config()
    if not isinstance(raw, dict):
        return dict(defaults)
    normalized: dict[str, object] = {}
    raw_val = raw.get("logToStdout", raw.get("log_to_stdout"))
    if raw_val is None:
        normalized["logToStdout"] = defaults["logToStdout"]
    else:
        if not isinstance(raw_val, str):
            raw_val = str(raw_val)
        norm = str(raw_val).strip().lower()
        if norm not in _LLAMA_SWAP_VALID_TOSTDOUT:
            normalized["logToStdout"] = defaults["logToStdout"]
        else:
            normalized["logToStdout"] = norm
    raw_level = raw.get("logLevel", raw.get("log_level"))
    if raw_level is None:
        normalized["logLevel"] = defaults["logLevel"]
    else:
        if not isinstance(raw_level, str):
            raw_level = str(raw_level)
        norm_level = str(raw_level).strip().lower()
        if norm_level not in _LLAMA_SWAP_VALID_LEVEL:
            normalized["logLevel"] = defaults["logLevel"]
        else:
            normalized["logLevel"] = norm_level
    for k in defaults:
        if k not in normalized:
            normalized[k] = defaults[k]
    return normalized


def _effective_llama_swap_config() -> dict[str, object]:
    try:
        from llamacpp_stack.cli.server_commands import _load_server_config_payload  # type: ignore

        payload = _load_server_config_payload(None)
    except Exception:
        try:
            import importlib.util
            import sys as _sys
            from pathlib import Path as _P

            fp = _P(__file__).parent.parent / "cli.py"
            spec = importlib.util.spec_from_file_location("llamacpp_stack._cli_file_tmp2", fp)
            if spec and spec.loader:
                cli_file = _sys.modules.get("llamacpp_stack._cli_file")
                if cli_file is not None and hasattr(cli_file, "_load_server_config_payload"):
                    payload = cli_file._load_server_config_payload(None)
                else:
                    payload = {}
            else:
                payload = {}
        except Exception:
            payload = {}
        if not payload:
            from .constants import PRODUCT_SLUG  # local import to avoid cycles

            for candidate in (
                Path.home() / ".config" / PRODUCT_SLUG / "conf.json",
                Path(f"/etc/{PRODUCT_SLUG}/conf.json"),
                Path.home() / ".config/heimdall-gateway/conf.json",  # legacy fallback
                Path("/etc/heimdall-gateway/conf.json"),  # legacy fallback
            ):
                try:
                    if candidate.exists():
                        import json as _json

                        payload = _json.loads(candidate.read_text(encoding="utf-8"))
                        break
                except Exception:
                    continue
    raw_logging = payload.get("logging") if isinstance(payload.get("logging"), dict) else {}
    raw_ls = raw_logging.get("llama_swap") if isinstance(raw_logging, dict) else None
    return _normalize_llama_swap_config(raw_ls)


def resolve_global_replica_config(args=None) -> dict[str, object]:
    try:
        from llamacpp_stack.cli.server_commands import _load_server_config_payload

        payload = _load_server_config_payload(args)
    except Exception:
        # Fallback: try via cli file cache
        try:
            import importlib.util
            import sys as _sys
            from pathlib import Path as _P

            fp = _P(__file__).parent.parent / "cli.py"
            spec = importlib.util.spec_from_file_location("llamacpp_stack._cli_file_tmp_replica", fp)
            if spec and spec.loader:
                # use cached file module if available
                cli_file = _sys.modules.get("llamacpp_stack._cli_file")
                if cli_file is not None and hasattr(cli_file, "_load_server_config_payload"):
                    payload = cli_file._load_server_config_payload(args)
                else:
                    payload = {}
            else:
                payload = {}
        except Exception:
            payload = {}
    raw = payload.get("replicas")
    return dict(raw) if isinstance(raw, dict) else {}


def get_model_replica_config(model: ManagedModel, global_raw: dict[str, object] | None = None, total_gpus: int | None = None) -> ReplicaConfig:
    explicit_global_config = global_raw is not None
    global_config: dict[str, object] = dict(global_raw if global_raw is not None else resolve_global_replica_config())
    raw: dict[str, object] = dict(global_config)
    model_raw: dict[str, object] = {}
    try:
        candidate = (model.server_overrides or {}).get("replicas")
        if isinstance(candidate, dict):
            model_raw = dict(candidate)
    except Exception:
        model_raw = {}
    model_enabled = model_raw.pop("enabled", None)
    raw.update(model_raw)
    cfg = ReplicaConfig()
    if explicit_global_config and "enabled" in global_config:
        cfg.enabled = _as_bool(global_config.get("enabled"), False)
    elif model_enabled is not None:
        cfg.enabled = _as_bool(model_enabled, False)
    else:
        cfg.enabled = _as_bool(global_config.get("enabled"), False)
    try:
        cfg.gpus_per_replica = max(1, int(raw.get("gpus_per_replica", _infer_base_gpu_count(model))))
    except Exception:
        cfg.gpus_per_replica = _infer_base_gpu_count(model)
    detected_total_gpus = total_gpus if total_gpus is not None else detect_cuda_device_count()
    auto_max = max(1, detected_total_gpus // max(1, cfg.gpus_per_replica)) if detected_total_gpus > 0 else cfg.max
    raw_max = raw.get("max", "auto" if cfg.enabled else cfg.max)
    try:
        if isinstance(raw_max, str) and raw_max.strip().lower() in {"auto", "", "none"}:
            cfg.max = auto_max
        else:
            cfg.max = max(1, int(raw_max))
    except Exception:
        cfg.max = auto_max
    placement = str(raw.get("placement", cfg.placement) or cfg.placement).strip().lower().replace("-", "_")
    if placement in {"exclusive_gpus", "pack_small_models"}:
        cfg.placement = placement
    try:
        cfg.safety_vram_mib = max(0, int(raw.get("safety_vram_mib", cfg.safety_vram_mib)))
    except Exception:
        pass
    try:
        cfg.max_models_per_gpu = max(1, int(raw.get("max_models_per_gpu", cfg.max_models_per_gpu)))
    except Exception:
        pass
    try:
        cfg.max_pack_fraction = max(0.01, min(1.0, float(raw.get("max_pack_fraction", cfg.max_pack_fraction))))
    except Exception:
        pass
    try:
        cfg.sticky_ttl_s = max(60, int(raw.get("sticky_ttl_s", cfg.sticky_ttl_s)))
    except Exception:
        pass
    return cfg


def replica_model_id(base_model_id: str, index: int) -> str:
    return f"{base_model_id}__replica_{index}"


def is_replica_model_id(model_id: str) -> bool:
    return bool(re.search(r"__replica_\d+$", str(model_id or "")))


def replica_base_model_id(model_id: str) -> str:
    return re.sub(r"__replica_\d+$", "", str(model_id or ""))


def _infer_base_gpu_count(model: ManagedModel) -> int:
    try:
        raw = (model.server_overrides or {}).get("gpu_count")
        if raw is not None:
            return max(1, int(raw))
    except Exception:
        pass
    try:
        ts = str((model.server_overrides or {}).get("tensor_split") or model.tensor_split or "1")
        parts = [p for p in ts.split(",") if p.strip()]
        return max(1, len(parts))
    except Exception:
        return 1


def _replica_gpu_sets(model: ManagedModel, cfg: ReplicaConfig, total_gpus: int | None = None) -> list[list[int]]:
    if not cfg.enabled or cfg.max <= 0:
        return []
    total = total_gpus if total_gpus is not None else detect_cuda_device_count()
    if total <= 0:
        total = max(cfg.gpus_per_replica, _infer_base_gpu_count(model))
    gpr = max(1, cfg.gpus_per_replica or _infer_base_gpu_count(model))
    sets: list[list[int]] = []
    if cfg.placement == "exclusive_gpus":
        base_gpu_count = max(0, _infer_base_gpu_count(model))
        if total <= base_gpu_count:
            return []
        for start in range(base_gpu_count, total, gpr):
            gpu_set = list(range(start, min(start + gpr, total)))
            if len(gpu_set) == gpr:
                sets.append(gpu_set)
            if len(sets) >= cfg.max:
                break
    else:
        for idx in range(cfg.max):
            if gpr == 1:
                sets.append([idx % total])
            else:
                start = (idx * gpr) % total
                gpu_set = [(start + off) % total for off in range(gpr)]
                if len(set(gpu_set)) == gpr:
                    sets.append(gpu_set)
    return sets[: cfg.max]


def _replica_overrides(base: ManagedModel, gpu_set: list[int]) -> dict[str, object]:
    overrides = dict(base.server_overrides or {})
    overrides.pop("replicas", None)
    if gpu_set:
        visible_count = len(gpu_set)
        overrides.pop("tensor_split", None)
        overrides["__replica_tensor_split"] = ",".join(["1"] * visible_count)
        overrides["main_gpu"] = 0
    return overrides


def build_replica_model(base: ManagedModel, index: int, gpu_set: list[int]) -> ManagedModel:
    return replace(
        base,
        model_id=replica_model_id(base.model_id, index),
        aliases=[],
        description=f"internal replica {index} of {base.model_id}",
        server_overrides=_replica_overrides(base, gpu_set),
    )


def _command_with_cuda_visible_devices(cmd: list[str], gpu_set: list[int]) -> list[str]:
    if not gpu_set:
        return cmd
    return ["/usr/bin/env", f"CUDA_VISIBLE_DEVICES={','.join(str(g) for g in gpu_set)}", *cmd]


def iter_catalog_with_replicas(catalog: list[ManagedModel], global_replica_config: dict[str, object] | None = None) -> list[tuple[ManagedModel, str | None, list[int] | None]]:
    """Return (model, public_base_model_id, gpu_set). public_base_model_id is set for internal replicas."""
    result: list[tuple[ManagedModel, str | None, list[int]]] = []
    for model in catalog:
        result.append((model, None, None))
        cfg = get_model_replica_config(model, global_replica_config)
        if not cfg.enabled:
            continue
        for idx, gpu_set in enumerate(_replica_gpu_sets(model, cfg)):
            result.append((build_replica_model(model, idx, gpu_set), model.model_id, gpu_set))
    return result


def iter_catalog_base_models(catalog: list[ManagedModel]) -> list[tuple[ManagedModel, str | None, list[int] | None]]:
    """Return only public/base catalog models for the static llama-swap config."""
    return [(model, None, None) for model in catalog]


def summarize_configured_replicas(catalog: list[ManagedModel], global_replica_config: dict[str, object] | None = None) -> list[str]:
    lines: list[str] = []
    total_gpus = detect_cuda_device_count()
    for model in catalog:
        cfg = get_model_replica_config(model, global_replica_config, total_gpus=total_gpus)
        if not cfg.enabled:
            continue
        gpu_sets = _replica_gpu_sets(model, cfg, total_gpus=total_gpus)
        if gpu_sets:
            lines.append(
                f"{model.model_id}: {len(gpu_sets)} replica(s), gpus_per_replica={cfg.gpus_per_replica}, gpu_sets={gpu_sets}"
            )
        else:
            lines.append(
                f"{model.model_id}: replicas enabled but no GPU set generated (gpus_per_replica={cfg.gpus_per_replica}, max={cfg.max})"
            )
    return lines


def _get_model_size_mib(m: ManagedModel) -> float:
    """Estimate model size in MiB for GGUF files and HF snapshots."""
    try:
        path = Path(m.local_path)
        if path.is_dir():
            return sum(
                file_path.stat().st_size
                for file_path in path.rglob("*")
                if file_path.is_file()
            ) / (1024 * 1024)
        return float(path.stat().st_size) / (1024 * 1024)
    except Exception:
        return 0.0


def _is_embedding_model(m: ManagedModel) -> bool:
    """Heuristic to identify if a model is an embedding model."""
    low_id = m.model_id.lower()
    if any(k in low_id for k in ["embedding", "bge-", "gte-", "snowflake-", "nomic-"]):
        return True
    for v in m.server_overrides.values():
        if isinstance(v, str) and "--embedding" in v:
            return True
    if "embedding" in (m.load_capabilities or []):
        return True
    return False


def _is_small_model(m: ManagedModel) -> bool:
    """Heuristic to identify if a model is 'small' and thus packable with others."""
    return _get_model_size_mib(m) < 4096.0


def _calculate_llama_swap_matrix(models_info: list[dict]) -> dict[str, object]:
    """
    Calculate the llama-swap matrix configuration to allow maximum concurrency.
    
    models_info is a list of dicts: {id, gpu_set, is_embedding, is_small, size_mib}

    Two extra rules exist on top of the plain "pack what fits" grouping:

    - A base and its own replicas are declared together, so scaling out never
      forces one of them to be evicted to load the other.
    - Any two large entries that own disjoint GPUs are also declared together.
      Without that, a base that spans every GPU makes its replicas incompatible
      with every other model, and asking for another model evicts the whole
      family instead of just the spare copy. An idle replica is additionally
      given half the eviction cost of its base, so the router drops the spare
      copy and keeps the original; requests for that model then queue on the
      original instead of paying for a full reload.
    """
    if not models_info:
        return {}
    sorted_ids = sorted({str(m["id"]) for m in models_info if str(m.get("id") or "").strip()})
    id_to_var = {model_id: f"m{idx}" for idx, model_id in enumerate(sorted_ids)}
    vars_map = {var_id: model_id for model_id, var_id in id_to_var.items()}
    embeddings = [m["id"] for m in models_info if m["is_embedding"]]
    smalls = [m["id"] for m in models_info if m["is_small"] and not m["is_embedding"]]
    larges = [m for m in models_info if not m["is_small"] and not m["is_embedding"]]
    packables = sorted(embeddings + smalls)
    large_groups: list[list[str]] = []
    all_known_gpus = set()
    for m in models_info:
        all_known_gpus.update(m["gpu_set"])
    for m in larges:
        if not m["gpu_set"]:
            m["_effective_gpu_set"] = set(all_known_gpus)
        else:
            m["_effective_gpu_set"] = set(m["gpu_set"])
    sorted_larges = sorted(larges, key=lambda x: len(x["_effective_gpu_set"]), reverse=True)
    for large in sorted_larges:
        added = False
        l_gpu_set = large["_effective_gpu_set"]
        for group in large_groups:
            conflict = False
            for existing_id in group:
                existing = next(m for m in models_info if m["id"] == existing_id)
                existing_gpus = existing.get("_effective_gpu_set", set(existing["gpu_set"]))
                if not existing_gpus and not existing["is_small"] and not existing["is_embedding"]:
                    existing_gpus = set(all_known_gpus)
                if l_gpu_set & existing_gpus:
                    conflict = True
                    break
            if not conflict:
                group.append(large["id"])
                added = True
                break
        if not added:
            large_groups.append([large["id"]])
    base_to_replicas: dict[str, list[str]] = {}
    for m in models_info:
        mid = m["id"]
        if is_replica_model_id(mid):
            base_to_replicas.setdefault(replica_base_model_id(mid), []).append(mid)

    def _resolve_group_gpus(model_id: str) -> set[int] | None:
        mi = next((x for x in models_info if x["id"] == model_id), None)
        if mi is None:
            return None
        gpus = set(mi.get("_effective_gpu_set") or set(mi.get("gpu_set") or []))
        if not gpus and not mi["is_small"] and not mi["is_embedding"]:
            return set(all_known_gpus)
        return gpus

    def _merge_group(members: list[str]) -> None:
        for group in large_groups:
            for mid in members:
                if mid in group:
                    group.remove(mid)
        large_groups[:] = [g for g in large_groups if g]
        large_groups.append(list(members))

    def _group_fits_disjointly(members: list[str]) -> bool:
        member_gpus = [_resolve_group_gpus(mid) for mid in members]
        if any(g is None for g in member_gpus):
            return False
        return all(
            member_gpus[i].isdisjoint(member_gpus[j])  # type: ignore[union-attr]
            for i in range(len(member_gpus))
            for j in range(i + 1, len(member_gpus))
        )

    for base, rids in base_to_replicas.items():
        members = [base, *rids]
        if not _group_fits_disjointly(members):
            continue
        _merge_group(members)
    cross_pairs: list[list[str]] = []
    for idx, first in enumerate(larges):
        first_gpus = set(first.get("_effective_gpu_set") or all_known_gpus)
        for second in larges[idx + 1:]:
            second_gpus = set(second.get("_effective_gpu_set") or all_known_gpus)
            if first_gpus.isdisjoint(second_gpus) and not any(set((first["id"], second["id"])) <= set(group) for group in large_groups):
                cross_pairs.append([first["id"], second["id"]])
    matrix_sets = {}
    for idx, group in enumerate(large_groups):
        group_vars = [id_to_var[model_id] for model_id in sorted(group + packables) if model_id in id_to_var]
        if group_vars:
            matrix_sets[f"group_{idx}"] = " & ".join(group_vars)
    for idx, pair in enumerate(cross_pairs):
        pair_vars = [id_to_var[model_id] for model_id in sorted(pair + packables) if model_id in id_to_var]
        if pair_vars:
            matrix_sets[f"pair_{idx}"] = " & ".join(pair_vars)
    if not large_groups and packables:
        packable_vars = [id_to_var[model_id] for model_id in packables if model_id in id_to_var]
        if packable_vars:
            matrix_sets["packables"] = " & ".join(packable_vars)
    evict_costs = {
        id_to_var[m["id"]]: max(1, int(m["size_mib"] * (0.5 if is_replica_model_id(m["id"]) else 1.0)))
        for m in models_info
        if m["id"] in id_to_var
    }
    return {
        "vars": vars_map,
        "sets": matrix_sets,
        "evict_costs": evict_costs
    }


def _model_info_for_matrix_entry(model_id: str, model_entry: dict, catalog_by_id: dict[str, ManagedModel]) -> dict:
    metadata = model_entry.get("metadata") if isinstance(model_entry, dict) else {}
    base_id = metadata.get("internal_replica_of") if isinstance(metadata, dict) else None
    model = catalog_by_id.get(str(base_id or model_id))
    cmd = str(model_entry.get("cmd") or "") if isinstance(model_entry, dict) else ""
    gpu_set: list[int] = []
    match = re.search(r"CUDA_VISIBLE_DEVICES=([0-9,]+)", cmd)
    if match:
        gpu_set = [int(part) for part in match.group(1).split(",") if part.strip().isdigit()]
    elif model is not None:
        gpu_set = list(range(max(0, detect_cuda_device_count())))
    return {
        "id": model_id,
        "gpu_set": gpu_set,
        "is_embedding": _is_embedding_model(model) if model is not None else False,
        "is_small": _is_small_model(model) if model is not None else False,
        "size_mib": _get_model_size_mib(model) if model is not None else 1,
    }


def _recalculate_llamaswap_matrix_from_config(data: dict, catalog: list[ManagedModel]) -> None:
    models = data.get("models")
    if not isinstance(models, dict):
        data.pop("matrix", None)
        return
    catalog_by_id = {model.model_id: model for model in catalog}
    infos = [_model_info_for_matrix_entry(str(model_id), entry, catalog_by_id) for model_id, entry in models.items() if isinstance(entry, dict)]
    matrix = _calculate_llama_swap_matrix(infos)
    if matrix:
        data["matrix"] = matrix
    else:
        data.pop("matrix", None)


def _get_cli_file():
    try:
        import importlib.util
        import sys as _sys
        from pathlib import Path as _P

        mod = _sys.modules.get("llamacpp_stack._cli_file")
        if mod is not None:
            return mod
        fp = _P(__file__).parent.parent / "cli.py"
        if not fp.exists():
            return None
        spec = importlib.util.spec_from_file_location("llamacpp_stack._cli_file", fp)
        if spec is None or spec.loader is None:
            return None
        m = importlib.util.module_from_spec(spec)
        _sys.modules["llamacpp_stack._cli_file"] = m
        spec.loader.exec_module(m)
        return m
    except Exception:
        return None


_ENGINE_DIR_NAMES = ("beellama", "buun", "exllama")


def _engine_binary_base(server_path: Path) -> Path:
    try:
        from llamacpp_stack.cli.server_commands import _engine_binary_anchor
    except Exception:
        # Same <root>/<engine>/bin climb as the helper: bare `parent` nests one level too deep.
        parent = server_path.parent
        if parent.name == "bin" and parent.parent.name in _ENGINE_DIR_NAMES:
            return parent.parent.parent
        return parent
    return _engine_binary_anchor(server_path)


def shell_quote(v):
    if re.fullmatch(r"\$\{[A-Za-z_][A-Za-z0-9_]*\}", v):
        return v
    if re.fullmatch(r"[A-Za-z0-9_./:=,+-]+", v):
        return v
    return "'" + v.replace("'", "'\"'\"'") + "'"


def render_llamaswap_config(
    catalog,
    path,
    server_path,
    start_port,
    idle_ttl=DEFAULT_IDLE_TTL,
    server_defaults: dict[str, object] | None = None,
    replica_defaults: dict[str, object] | None = None,
):
    # Lazy imports to avoid cycle with server_commands
    try:
        from llamacpp_stack.cli.server_commands import (
            build_llama_server_command,
            normalize_server_overrides,
            resolve_llama_server_defaults,
            resolve_vllm_defaults,
            server_supports_flag,
        )
    except Exception:
        cli_file = _get_cli_file()
        build_llama_server_command = getattr(cli_file, "build_llama_server_command")
        normalize_server_overrides = getattr(cli_file, "normalize_server_overrides")
        resolve_llama_server_defaults = getattr(cli_file, "resolve_llama_server_defaults")
        resolve_vllm_defaults = getattr(cli_file, "resolve_vllm_defaults")
        server_supports_flag = getattr(cli_file, "server_supports_flag")

    try:
        import yaml  # type: ignore
    except Exception:
        yaml = None  # type: ignore

    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        _ls = _effective_llama_swap_config()
    except Exception:
        _ls = _default_llama_swap_config()
    data = {
        "healthCheckTimeout": 600,
        "logLevel": str(_ls.get("logLevel", "info")),
        "logToStdout": str(_ls.get("logToStdout", "both")),
        "startPort": start_port,
        "sendLoadingState": False,
        "includeAliasesInList": True,
        "models": {},
    }
    resolved_defaults = normalize_server_overrides(server_defaults or resolve_llama_server_defaults())
    resolved_vllm_defaults = resolve_vllm_defaults()
    path_usage: dict[str, int] = {}
    resolved_paths: dict[str, Path] = {}
    for m in catalog:
        try:
            p = Path(m.local_path).resolve()
            key = str(p)
        except Exception:
            key = str(m.local_path or "")
        path_usage[key] = path_usage.get(key, 0) + 1
        resolved_paths[key] = Path(m.local_path) if m.local_path else Path("")
    replica_group_members: list[str] = []
    models_info_for_matrix: list[dict] = []
    mmproj_config = cached_mmproj_config()

    def _render_cmd(use_model, include_mmproj: bool) -> list[str]:
        engine = str((getattr(use_model, "server_overrides", {}) or {}).get("engine") or "").strip().lower().replace("_", "-")
        if engine in {"exllamav3", "exllama-v3", "exllama3"}:
            engine = "exllama"
        if engine in {"buun-beta"}:
            engine = "buun"
        effective_server_path = server_path
        if engine == "buun":
            candidate = _engine_binary_base(Path(server_path)) / "buun" / "bin" / "llama-server-buun"
            if candidate.exists():
                effective_server_path = str(candidate)
                print(f"[buun] {use_model.model_id} -> {effective_server_path}", flush=True)
        elif engine == "beellama":
            candidate = _engine_binary_base(Path(server_path)) / "beellama" / "bin" / "llama-server-beellama"
            if candidate.exists():
                effective_server_path = str(candidate)
                print(f"[beellama] {use_model.model_id} -> {effective_server_path}", flush=True)
        elif engine == "exllama":
            candidate = _engine_binary_base(Path(server_path)) / "exllama" / "bin" / "llama-server-exllama"
            if candidate.exists():
                effective_server_path = str(candidate)
                print(f"[exllama] {use_model.model_id} -> {effective_server_path}", flush=True)
        rendered = build_llama_server_command(
            use_model,
            effective_server_path,
            port="${PORT}",
            include_mmproj=include_mmproj,
            server_defaults=resolved_defaults,
            vllm_defaults=resolved_vllm_defaults,
        )
        try:
            ct = str((getattr(use_model, "server_overrides", {}) or {}).get("cache_type") or "").strip().lower()
            if engine == "buun" and ct in {"turbo8","turbo4","turbo3","turbo2","turbo3_tcq","turbo2_tcq","turbo1_tcq","vbr"}:
                filtered: list[str] = []
                skip = False
                for idx, part in enumerate(rendered):
                    if skip:
                        skip = False
                        continue
                    if part in {"--cache-type-k","--cache-type-v"}:
                        nxt = rendered[idx+1] if idx+1 < len(rendered) else ""
                        if nxt.strip().lower() == "f16":
                            skip = True
                            continue
                    filtered.append(part)
                rendered = filtered
        except Exception:
            pass
        return rendered

    for m, public_base_model_id, replica_gpu_set in sorted(iter_catalog_base_models(catalog), key=lambda item: item[0].model_id):
        use_model = m
        cmd = _render_cmd(use_model, bool(resolve_render_include_mmproj(use_model, mmproj_config)))
        if public_base_model_id is not None:
            cmd = _command_with_cuda_visible_devices(cmd, replica_gpu_set)
            replica_group_members.append(m.model_id)
        models_info_for_matrix.append({
            "id": m.model_id,
            "gpu_set": replica_gpu_set if replica_gpu_set is not None else list(range(detect_cuda_device_count())),
            "is_embedding": _is_embedding_model(m),
            "is_small": _is_small_model(m),
            "size_mib": _get_model_size_mib(m)
        })
        try:
            derived = str(m.model_id).endswith("+template") or str(m.model_id).endswith("+spec") or bool(m.speculative)
            if derived:
                name_flags = ["--model-id", "--model-name", "--name", "--publish-name", "--publish-id"]
                chosen_flag = None
                for f in name_flags:
                    if server_supports_flag(server_path, f):
                        chosen_flag = f
                        break
                if chosen_flag:
                    cli_file2 = _get_cli_file()
                    _canonical = getattr(cli_file2, "_canonical_model_ref", lambda x: x)
                    safe_name = _canonical(m.model_id)
                    cmd.extend([chosen_flag, safe_name])
        except Exception:
            pass
        entry = {
            "cmd": " ".join(shell_quote(part) for part in cmd),
            "checkEndpoint": "/health",
            "ttl": int(idle_ttl),
        }
        entry["capabilities"] = route_capabilities(entry)
        data["models"][m.model_id] = entry
        if public_base_model_id is not None:
            data["models"][m.model_id]["metadata"] = {"internal_replica_of": public_base_model_id}
        if public_base_model_id is None and m.aliases:
            data["models"][m.model_id]["aliases"] = m.aliases
        if m.description:
            data["models"][m.model_id]["description"] = m.description
    matrix_config = _calculate_llama_swap_matrix(models_info_for_matrix)
    if matrix_config:
        data["matrix"] = matrix_config
    tmp = path.with_suffix(".tmp")
    with tmp.open("w", encoding="utf-8") as file_handle:
        file_handle.write(LLAMASWAP_CONFIG_HEADER)
        if yaml is not None:
            yaml.safe_dump(data, file_handle, sort_keys=False)
        else:
            import json as _json

            file_handle.write(_json.dumps(data, indent=2))
    tmp.replace(path)


def _render_instance_command(
    model: ManagedModel,
    server_path: Path | str,
    server_defaults: dict[str, object] | None = None,
    include_mmproj: bool = False,
) -> list[str]:
    """Build the llama-swap ``cmd`` for one base-or-replica route."""
    try:
        from llamacpp_stack.cli.server_commands import (
            build_llama_server_command as _build_cmd,
            normalize_server_overrides as _norm,
            resolve_llama_server_defaults as _resolve_defaults,
            resolve_vllm_defaults as _resolve_vllm,
        )
    except Exception:
        cli_file = _get_cli_file()
        _build_cmd = getattr(cli_file, "build_llama_server_command")
        _norm = getattr(cli_file, "normalize_server_overrides")
        _resolve_defaults = getattr(cli_file, "resolve_llama_server_defaults")
        _resolve_vllm = getattr(cli_file, "resolve_vllm_defaults")

    engine = str((getattr(model, "server_overrides", {}) or {}).get("engine") or "").strip().lower().replace("_", "-")
    if engine in {"exllamav3", "exllama-v3", "exllama3"}:
        engine = "exllama"
    if engine in {"buun-beta"}:
        engine = "buun"
    effective_server_path = Path(server_path)
    if engine == "buun":
        cand = _engine_binary_base(Path(server_path)) / "buun" / "bin" / "llama-server-buun"
        if cand.exists():
            effective_server_path = cand
            print(f"[buun] {model.model_id} -> {effective_server_path}", flush=True)
    elif engine == "beellama":
        cand = _engine_binary_base(Path(server_path)) / "beellama" / "bin" / "llama-server-beellama"
        if cand.exists():
            effective_server_path = cand
    elif engine == "exllama":
        cand = _engine_binary_base(Path(server_path)) / "exllama" / "bin" / "llama-server-exllama"
        if cand.exists():
            effective_server_path = cand
            print(f"[exllama] {model.model_id} -> {effective_server_path}", flush=True)
    cmd = _build_cmd(
        model,
        Path(effective_server_path),
        port="${PORT}",
        server_defaults=_norm(server_defaults or _resolve_defaults()),
        vllm_defaults=_resolve_vllm(),
        include_mmproj=bool(include_mmproj),
    )
    try:
        cache_type = str((getattr(model, "server_overrides", {}) or {}).get("cache_type") or "").strip().lower()
        if engine == "buun" and cache_type in {"turbo8","turbo4","turbo3","turbo2","turbo3_tcq","turbo2_tcq","turbo1_tcq","vbr"}:
            filtered: list[str] = []
            skip = False
            for j, part in enumerate(cmd):
                if skip:
                    skip = False
                    continue
                if part in {"--cache-type-k", "--cache-type-v"} and j + 1 < len(cmd) and cmd[j + 1].strip().lower() == "f16":
                    skip = True
                    continue
                filtered.append(part)
            cmd = filtered
    except Exception:
        pass
    return cmd


def route_carries_mmproj(entry: object) -> bool:
    """True when a rendered route entry's command carries ``--mmproj``."""
    try:
        return "--mmproj" in str((entry or {}).get("cmd") or "")
    except Exception:
        return False


def route_capabilities(entry: object) -> dict[str, object]:
    """llama-swap listing capabilities for a rendered route entry.

    llama-swap publishes this through ``/v1/models`` and badges it in the v255
    web UI, so deriving ``vision`` from the route's own command makes a lazy
    model report ``vision: false`` until the projector is attached to that
    instance and ``vision: true`` only on the one that actually carries it.
    Listing metadata only: llama-swap never routes on it.
    """
    return {"vision": route_carries_mmproj(entry)}


def _replica_index_for_model_id(model_id: str) -> int:
    match = re.search(r"__replica_(\d+)$", str(model_id or ""))
    try:
        return int(match.group(1)) if match else 0
    except (TypeError, ValueError):
        return 0


def ensure_internal_route_in_llamaswap_config(
    base_model: ManagedModel,
    route_id: str,
    catalog: list[ManagedModel],
    config_path: Path | str,
    server_path: Path | str,
    idle_ttl: int,
    server_defaults: dict[str, object] | None = None,
    *,
    gpu_set: list[int] | None = None,
    include_mmproj: bool = False,
    metadata: dict[str, object] | None = None,
    description: str | None = None,
    ttl: int | None = None,
) -> str:
    """Create or refresh one internal route, which may be a replica or the base.

    Returns ``route_id``. An entry that already exists with the requested
    projector state is left untouched, so ordinary traffic never rewrites the
    watched config. The base route is rendered from ``base_model`` itself, which
    is what makes it possible to bolt the projector onto whichever instance is
    idle at request time.
    """
    try:
        import yaml  # type: ignore
    except Exception:
        yaml = None  # type: ignore

    path = Path(config_path)
    route_id = str(route_id or "")
    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        if yaml is not None:
            data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        else:
            import json as _json

            data = _json.loads(path.read_text(encoding="utf-8")) or {}
    except Exception:
        data = {}
    if not isinstance(data, dict):
        data = {}
    try:
        _ls2 = _effective_llama_swap_config()
    except Exception:
        _ls2 = _default_llama_swap_config()
    data.setdefault("healthCheckTimeout", 600)
    data.setdefault("logLevel", str(_ls2.get("logLevel", "info")))
    data.setdefault("logToStdout", str(_ls2.get("logToStdout", "both")))
    data.setdefault("sendLoadingState", False)
    data.setdefault("includeAliasesInList", True)
    models = data.setdefault("models", {})
    if not isinstance(models, dict):
        models = {}
        data["models"] = models

    want_mmproj = bool(include_mmproj)
    existing = models.get(route_id)
    if isinstance(existing, dict) and route_carries_mmproj(existing) == want_mmproj:
        return route_id

    route_gpu_set: list[int] = []
    if route_id == base_model.model_id:
        model_for_route = base_model
    else:
        route_gpu_set = list(gpu_set or [])
        model_for_route = build_replica_model(base_model, _replica_index_for_model_id(route_id), route_gpu_set)

    cmd = _render_instance_command(model_for_route, server_path, server_defaults, want_mmproj)
    if route_gpu_set:
        cmd = _command_with_cuda_visible_devices(cmd, route_gpu_set)
    entry = {
        "cmd": " ".join(shell_quote(part) for part in cmd),
        "checkEndpoint": "/health",
        "ttl": int(ttl if ttl else idle_ttl),
        "metadata": dict(metadata or {"internal_replica_of": base_model.model_id}),
        "description": description or getattr(model_for_route, "description", "") or route_id,
    }
    entry["capabilities"] = route_capabilities(entry)
    models[route_id] = entry
    _recalculate_llamaswap_matrix_from_config(data, catalog)
    tmp = path.with_suffix(".tmp")
    with tmp.open("w", encoding="utf-8") as file_handle:
        file_handle.write(LLAMASWAP_CONFIG_HEADER)
        if yaml is not None:
            yaml.safe_dump(data, file_handle, sort_keys=False)
        else:
            import json as _json

            file_handle.write(_json.dumps(data, indent=2))
    tmp.replace(path)
    try:
        cli_file3 = _get_cli_file()
        _log = getattr(cli_file3, "log_api_event", None)
        if _log is not None:
            _log(
                "internal_route_refreshed",
                {"model": base_model.model_id, "route": route_id, "mmproj": want_mmproj, "config_path": str(path)},
            )
    except Exception:
        pass
    return route_id


def drop_internal_route_from_llamaswap_config(
    base_model: ManagedModel,
    route_id: str,
    catalog: list[ManagedModel],
    config_path: Path | str,
    *,
    allow_base: bool = False,
) -> bool:
    """Remove one internal route so llama-swap stops the process serving it.

    Returns ``True`` when the config was rewritten. This exists because
    llama-swap applies a changed ``cmd`` only the *next* time a route is loaded:
    it does not restart an already-running process. So bolting the projector onto
    an instance that is currently serving means the running copy keeps its old,
    projector-less argv. Dropping the route and then re-adding it (see
    ``ensure_internal_route_in_llamaswap_config``) is what forces the reload, so
    the caller MUST re-add the route afterwards or the model goes unpublished.

    The base route needs ``allow_base=True`` because it is the one route that is
    not recreated on demand; the default keeps it safe against accidental loss.
    """
    route_id = str(route_id or "")
    if not route_id:
        return False
    if route_id == getattr(base_model, "model_id", "") and not allow_base:
        return False
    try:
        import yaml  # type: ignore
    except Exception:
        yaml = None  # type: ignore

    path = Path(config_path)
    try:
        if yaml is not None:
            data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        else:
            import json as _json

            data = _json.loads(path.read_text(encoding="utf-8")) or {}
    except Exception:
        return False
    models = (data or {}).get("models") if isinstance(data, dict) else None
    if not isinstance(models, dict) or route_id not in models:
        return False

    models.pop(route_id, None)
    _recalculate_llamaswap_matrix_from_config(data, catalog)
    tmp = path.with_suffix(".tmp")
    with tmp.open("w", encoding="utf-8") as file_handle:
        file_handle.write(LLAMASWAP_CONFIG_HEADER)
        if yaml is not None:
            yaml.safe_dump(data, file_handle, sort_keys=False)
        else:
            import json as _json

            file_handle.write(_json.dumps(data, indent=2))
    tmp.replace(path)
    try:
        cli_file3 = _get_cli_file()
        _log = getattr(cli_file3, "log_api_event", None)
        if _log is not None:
            _log(
                "internal_route_dropped",
                {"model": base_model.model_id, "route": route_id, "config_path": str(path)},
            )
    except Exception:
        pass
    return True


def ensure_replica_route_in_llamaswap_config(
    base_model: ManagedModel,
    replica_index: int,
    gpu_set: list[int],
    catalog: list[ManagedModel],
    config_path: Path | str,
    server_path: Path | str,
    idle_ttl: int,
    server_defaults: dict[str, object] | None = None,
    *,
    include_mmproj: bool | None = None,
) -> str:
    """Create one internal replica route in config.yaml and let llama-swap --watch-config reload it."""
    rid = replica_model_id(base_model.model_id, replica_index)
    if include_mmproj is None:
        include_mmproj = bool(resolve_render_include_mmproj(base_model, cached_mmproj_config()))
    return ensure_internal_route_in_llamaswap_config(
        base_model,
        rid,
        catalog,
        config_path,
        server_path,
        idle_ttl,
        server_defaults,
        gpu_set=list(gpu_set or []),
        include_mmproj=bool(include_mmproj),
    )


# Alias for backwards compat
ensure_replica_route = ensure_replica_route_in_llamaswap_config


def set_instance_mmproj_in_llamaswap_config(
    base_model: ManagedModel,
    instance_id: str,
    catalog: list[ManagedModel],
    config_path: Path | str,
    server_path: Path | str,
    idle_ttl: int,
    server_defaults: dict[str, object] | None = None,
    *,
    enable: bool,
    gpu_set: list[int] | None = None,
) -> str:
    """Attach (or detach) ``--mmproj`` on exactly one route of ``base_model``.

    ``instance_id`` is the base id or one of its ``__replica_N`` ids. While the
    projector is attached the route also gets the vision TTL, so llama-swap
    unloads it once the image path has been idle long enough; the caller then
    calls this again with ``enable=False`` to hand the instance back to text.
    """
    ttl = int(idle_ttl)
    if enable:
        try:
            vision_ttl = vision_route_ttl(cached_mmproj_config())
        except Exception:
            vision_ttl = None
        if vision_ttl:
            ttl = int(vision_ttl)
    metadata = {"internal_replica_of": base_model.model_id}
    if enable:
        metadata["vision_variant"] = True
    return ensure_internal_route_in_llamaswap_config(
        base_model,
        instance_id,
        catalog,
        config_path,
        server_path,
        int(idle_ttl),
        server_defaults,
        gpu_set=list(gpu_set or []),
        include_mmproj=bool(enable),
        metadata=metadata,
        ttl=ttl,
    )


__all__ = [
    "LLAMASWAP_CONFIG_HEADER",
    "resolve_global_replica_config",
    "get_model_replica_config",
    "replica_model_id",
    "is_replica_model_id",
    "replica_base_model_id",
    "build_replica_model",
    "iter_catalog_with_replicas",
    "iter_catalog_base_models",
    "summarize_configured_replicas",
    "_get_model_size_mib",
    "_is_embedding_model",
    "_is_small_model",
    "_calculate_llama_swap_matrix",
    "render_llamaswap_config",
    "_model_info_for_matrix_entry",
    "ensure_replica_route_in_llamaswap_config",
    "ensure_replica_route",
    "drop_internal_route_from_llamaswap_config",
    "ensure_internal_route_in_llamaswap_config",
    "set_instance_mmproj_in_llamaswap_config",
    "route_carries_mmproj",
    "route_capabilities",
    "shell_quote",
]
